// <auto-generated />
namespace EMarket.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addDataAnnotationForNewVar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addDataAnnotationForNewVar));
        
        string IMigrationMetadata.Id
        {
            get { return "202003281933306_addDataAnnotationForNewVar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
